### PR TITLE
chore: dependency on protobuf library made compile-only

### PR DESCRIPTION
**Pull request by augi**
[As you can see in the pom.xml](https://repo1.maven.org/maven2/com/avast/bytes/bytes-gpb/2.1.2/bytes-gpb-2.1.2.pom), the dependency on Protobuf library is _hard_.

IMHO it would be better to make it _optional_. 

I'm raising this PR because due to this, our projects are reported as vulnerable because `com.google.protobuf:protobuf-java:2.6.1` contains a vulnerability.

So also updating this dependency to a newer version would solve our problem.

### CODE REVIEW

**Comment by jakubjanecek** [comment]
I don't think this is right. `bytes-core` does not depend on GPB but `bytes-gpb` depends on it and it is a hard dependency because without it it wouldn't work at all - you would encounter runtime errors.

**Comment by jakubjanecek** [comment]
I think we could create another module with GPBv3 which would solve your problem most probably.

**Comment by augi** [comment]
> I don't think this is right. `bytes-core` does not depend on GPB but `bytes-gpb` depends on it and it is a hard dependency because without it it wouldn't work at all - you would encounter runtime errors.

I'm updating the settings of the `gpb` project, not the `core`.

After my change, the user of the library would be responsible for providing the `protobuf-java` dependency.

**Comment by jakubjanecek** [comment]
I understand that but don't you think that it would make the library very hard to use? Why would the user of the library should provide a dependency? This is done when your library has some optional feature which you can enable by adding another dependency in runtime but the sole purpose of this library is to provide integration between `Bytes` and `ByteString` from GPB library so without that dependency this library won't work at all. This is not the right use case for optional dependency.

I understand there is some potential security risk but unfortunately GPB 2.6.1 is the latest version in the `2.x` line and some poeple still need it. What I can offer is to create another module with GPB `3.x` and the user can choose which of these versions is right for them - unfortunately they are not binary compatible so they can't be used both.

**Comment by jendakol** [comment]
I don't like these optional dependencies where they are not really optional - which is the case :-(  
Are you @augi sure one can't have a runtime explosion when having it optional (e.g. he can't use anything from the `gpb` submodule without having GPB dependency included)?

**Comment by augi** [comment]
You are right that an optional dependency would be more appropriate provided the GPB-specific code would be in the `core` module.

So feel free to create a new module for GPB 3.x (I tried it myself but sbt doesn't look like working on any of my Windows machines 😞)

**Comment by jakubjanecek** [comment]
Version `2.2.0` should help you out.

**Pull request closed without merging**
